### PR TITLE
Define env: github.PYPRESENCE_CLIENT_ID

### PR DESCRIPTION
**Pull request by cclauss**
As discussed at https://github.com/qwertyquerty/pypresence/pull/131#issuecomment-929657322 a maintainer of this repo will need to add the corresponding GitHub secret.

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Why the hell are you installing d.py

**Comment by cclauss** [comment]
Because the error is that discord cannot be found.

**Comment by LewdNeko** [comment]
What

**Comment by qwertyquerty** [comment]
You absolute mongoloid it's talking about the actual discord client. You would need a running discord client on the VM that is presently *logged in* to an account to actually unit test this stuff. I don't even know what you're trying to accomplish here.

**Comment by LewdNeko** [comment]
The most achievable here is ensuring that it *does* error when run on a machine with no Discord RPC acailable

**Comment by qwertyquerty** [comment]
Did you miss the part where I said *logged in*

**Pull request closed without merging**
