### PR TITLE
PyPI packaging improvements

### PR DESCRIPTION
**Pull request by GhostofGoes**
Improved the setuptools packaging that's used by PyPI (which is where most people will be installing from with `pip install pypresence`).

Summary
* Changed the description to be the full README contents
* Added classifiers and keywords to improve discoverability
* Added python_requires to help pip PEP 440)
* Added zip_safe flag since we're not accessing distributed files or anything
* Added LICENSE to package metadata
* Ensure universal wheels are always generated (better compatibility)
* Add a shorthand to cut a release (`python setup.py release`)

To publish a release:
```bash
python setup.py release
twine upload dist/*
```

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Is this tested?

**Comment by GhostofGoes** [comment]
No, I didn't have a chance to last night. Figured I'd throw it up and get some feedback. I'll test it in a bit.

**Comment by GhostofGoes** [comment]
What's the downside of having the long description on PyPI? I know many people (myself included) either actively search for Python packages on there (especially after the overhaul) or it's the first page we land on from Google/DDG.

**Comment by GhostofGoes** [comment]
Tested. It builds without issues, is pip install-able, and works just fine as a package (and thankfully 3.0.0 didn't break anything in my project 😅)

**Comment by qwertyquerty** [comment]
I don't see a downside, so I'll merge

**Comment by qwertyquerty** [comment]
This will be live with 3.1

**Comment by GhostofGoes** [comment]
Awesome 👍

**Pull request merged**
