### PR TITLE
Add flatpak'ed Discord support

### PR DESCRIPTION
**Pull request by gasinvein**
~~This depends on flathub/com.discordapp.Discord#68~~.

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Neko what do you think

**Comment by LewdNeko** [comment]
What's a flakpak? How commonplace is it? Is their userbase sufficient? Doesn't look it.

**Comment by gasinvein** [comment]
[Flatpak](https://flatpak.org/) is a technology for distributing desktop apps for Linux. It's widely adopted by linux distributions, some of them (e.g. Endless OS) use it as primary package format.

**Comment by LewdNeko** [comment]
We're getting a lot of these custom distributions appearing and it's getting tiresome supporting them - I don't think I want to support every man and their dog's implementation of app distribution until a standard is established.

**Comment by gasinvein** [comment]
There are only two which require any specific support - Flatpak and Snap. And support here means handling another possible path of socket.

**Comment by GhostofGoes** [comment]
This looks fine to me. Flatpak is the primary app packaging alternative to Snap in the Linux ecosystem, and sees a lot of use on distros like Fedora, so it makes sense to have a few lines to properly support it.

**Pull request merged**
