### PR TITLE
Type annotations and other improvements

### PR DESCRIPTION
**Pull request by GhostofGoes**
Got bored and figured I'd hack on this a bit.

Summary
* Added type annotations to most of the method arguments. These are useful for linters, people reading the code, and various other purposes. I followed what was in the README for guidance.
* Fixed a potential Python 3.5 incompatibility in BaseClient (3.6 introduced argument annotations)
* Some formatting improvements
* Cleaned up build artifacts (`dist/` being the main offender)
* Make imports a little cleaner

### CODE REVIEW

**Comment by qwertyquerty** [comment]
Wow, this sure is a lot of changes, have you tested this thoroughly on 3.5, 6, and 7?

**Comment by GhostofGoes** [comment]
Ok, now I'm sure. Tested on 3.5, 3.6, and 3.7 (using venvs) against all 3 examples and my personal project. Going to add a tox.ini file to make this less painful...

**Comment by qwertyquerty** [comment]
I prefer to keep the dist/ in the repo. Fix that and I will merge

**Comment by GhostofGoes** [comment]
They're back and beautiful

**Comment by qwertyquerty** [comment]
Will be implemented in 3.1.1

**Pull request merged**
