### PR TITLE
Fix Fix select_voice_channel not disconnecting channel_id is None + add "force" parameter

### PR DESCRIPTION
**Pull request by Sebclem**
Hi,
I have fixed a little issue with select_voice_channel:
When channel_id is None, the user is not disconnected and you have an error message that the user is allready connected to a voice channel. 

I have also added the "force" parameter that I mention on #122

### CODE REVIEW

**Comment by Sebclem** [comment]
I don't know if you want to use the master or dev branche as base, so let me know

**Comment by LewdNeko** [comment]
Dev branch is fine

**Comment by LewdNeko** [comment]
LGTM

**Comment by LewdNeko** [comment]
Please update your PR to make sure any changes to pypresence.Client are reflected in pypresence.AioClient.

**Comment by Sebclem** [comment]
Sorry i haven't seen that there was this other client, it's done

**Review by cosmofm — COMMENTED** [review]
please add more explanation.

**Review by LewdNeko — APPROVED** [review]

**Comment by Sebclem** [comment]
@qwertyquerty Are you okay with those changes ?

**Pull request merged**
