### PR TITLE
Removed the loop parameter

### PR DESCRIPTION
**Pull request by Hunter2807**
Since 3.8, the loop parameter is depreceated. Almost no module right now is supporting 3.7, so why not just remove the support for that too?

### CODE REVIEW

**Comment by LewdNeko** [comment]
Please could you also reflect us removing support for 3.7 and prior in the following files:
- [CONTRIBUTING.md](https://github.com/qwertyquerty/pypresence/blob/master/CONTRIBUTING.md)
- [README.md](https://github.com/qwertyquerty/pypresence/blob/master/README.md) (Use the note section maybe?)

**Review by LewdNeko — CHANGES_REQUESTED** [review]
See prior comment

**Comment by Hunter2807** [comment]
Oh sure! Lemme do it

**Comment by Hunter2807** [comment]
There! Made some more changes regarding Python versions

**Review by Hunter2807 — COMMENTED** [review]
Bro I fixed all this versions and stuff before you requested the changes. Please merge the PR

**Review by LewdNeko — APPROVED** [review]

**Pull request merged**
