### PR TITLE
Use a more widely accepted syntax for docs

### PR DESCRIPTION
**Pull request by kot83**
Generally, people use `Instance#method` for instances of a class/object.

### CODE REVIEW

**Comment by LewdNeko** [comment]
I have never, ever seen this. Anywhere.

**Comment by kot83** [comment]
It's fairly common, go search for it :)

**Comment by LewdNeko** [comment]
These docs are now deprecated, anyway. The docs are pretty much fully available online, so this is an unneeded change.
Thanks anyway, I'll look into using `Instance#method` despite never seeing it anywhere and not being a huge fan of how it looks.

**Comment by kot83** [comment]
Right, have a look at this too: https://stackoverflow.com/questions/2587896/referring-to-javascript-instance-methods-with-a-pound-hash-sign

**Comment by LewdNeko** [comment]
Thanks

**Comment by qwertyquerty** [comment]
we do not serve kindly to those of the religion of js here

**Pull request closed without merging**
